# Generated by Django 2.2 on 2021-06-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureapp', '0002_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to='pictureapp.User'),
        ),
    ]
