# Generated by Django 2.2 on 2021-06-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureapp', '0003_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='(555)555-5555', max_length=255),
        ),
    ]
